"""
cortex.doc_generator
--------------------
**Fallback** documentation generator for PR context and pipeline results.

This module is only used when the PR does **not** include agent-generated
documentation. The preferred flow is:

1. Developer works with their AI agent (Copilot, Claude Code, Cursor, Qwen, etc.)
2. At end of day, the agent writes documentation directly to vault/ using its
   Obsidian Markdown skills
3. Developer commits code + docs together
4. When the PR opens, Cortex **verifies** if agent docs exist:
   - YES → index them as semantic memory
   - NO  → generate this fallback (single session note) so the day's work
           isn't lost

Fallback document type
----------------------
- session → vault/sessions/     (only doc type generated in fallback mode)

Usage
-----
    from cortex.doc_generator import DocGenerator
    from cortex.pr_capture import capture_manual

    ctx = capture_manual(title="Fix login bug", ...)
    gen = DocGenerator(vault_path="vault")
    docs = gen.generate_all(ctx)  # only session notes in fallback mode
    gen.write_docs(docs)
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from cortex.models import GeneratedDoc, PRContext

# ------------------------------------------------------------------
# Fallback session template
# ------------------------------------------------------------------

_TEMPLATE_SESSION = """\
---
title: "{{title}}"
date: {{date}}
pr: "#{{pr_number}}"
author: {{author}}
branch: {{source_branch}}
commit: {{commit_sha}}
tags: [session{{tags}}]
status: fallback
---
# {{title}}

> [!warning] Fallback Documentation
> This note was auto-generated by Cortex because no agent-written
> documentation was found in this PR. Consider writing proper docs
> next time using your AI agent's Obsidian Markdown skills.

## Summary
{{body_summary}}

## Changes
{{diff_summary}}

## Pipeline Results
| Check | Result |
|-------|--------|
| Lint (SAST) | {{lint_result}} |
| Audit (SCA) | {{audit_result}} |
| Tests | {{test_result}} |

## Files Modified
{{files_list}}
"""


# ------------------------------------------------------------------
# DocGenerator (fallback mode)
# ------------------------------------------------------------------

class DocGenerator:
    """
    Generates **fallback** documentation from PR context.

    Only produces session notes. The primary documentation should come
    from the AI agent that the developer works with during their day.
    """

    def __init__(self, vault_path: str | Path = "vault") -> None:
        self.vault_path = Path(vault_path)

    def _safe_filename(self, title: str) -> str:
        """Convert a title to a safe markdown filename."""
        name = re.sub(r"[^\w\s-]", "", title.lower().strip())
        name = re.sub(r"[\s]+", "-", name)
        name = name[:80]
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        return f"{today}_{name}.md" if name else f"{today}.md"

    def _render(self, template: str, **kwargs: str) -> str:
        """Simple template rendering."""
        result = template
        for key, value in kwargs.items():
            result = result.replace(f"{{{{{key}}}}}", str(value))
        result = re.sub(r"\{\{[^}]*\}\}", "N/A", result)
        return result

    def generate_session(self, ctx: PRContext) -> GeneratedDoc:
        """Generate a fallback session note."""
        body_summary = ctx.body[:300] if ctx.body else "No description provided."
        files_list = "\n".join(f"- `{f}`" for f in ctx.files_changed[:20]) or "- (none)"
        tags = "".join(f", {lbl}" for lbl in ctx.labels[:5]) if ctx.labels else ""

        content = self._render(
            _TEMPLATE_SESSION,
            title=ctx.title,
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            pr_number=str(ctx.pr_number),
            author=ctx.author,
            source_branch=ctx.source_branch,
            commit_sha=ctx.commit_sha[:8],
            tags=tags,
            body_summary=body_summary,
            diff_summary=ctx.diff_summary or "(no diff summary)",
            lint_result=ctx.lint_result or "not run",
            audit_result=ctx.audit_result or "not run",
            test_result=ctx.test_result or "not run",
            files_list=files_list,
        )

        return GeneratedDoc(
            doc_type="session",
            title=ctx.title,
            content=content,
            vault_subfolder="sessions",
            filename=self._safe_filename(ctx.title),
        )

    def generate_all(
        self,
        ctx: PRContext,
        *,
        skip_types: list[str] | None = None,
    ) -> list[GeneratedDoc]:
        """
        Generate fallback session note.

        In fallback mode, only session notes are generated.
        """
        skip = set(skip_types or [])
        docs: list[GeneratedDoc] = []

        if "session" not in skip:
            docs.append(self.generate_session(ctx))

        return docs

    def write_docs(self, docs: list[GeneratedDoc]) -> list[Path]:
        """Write generated documents to the vault."""
        written = []
        for doc in docs:
            target_dir = self.vault_path / doc.vault_subfolder
            target_dir.mkdir(parents=True, exist_ok=True)
            target_file = target_dir / doc.filename
            target_file.write_text(doc.content, encoding="utf-8")
            written.append(target_file)
        return written

    def generate_and_write(self, ctx: PRContext, **kwargs: Any) -> list[Path]:
        """One-shot: generate all docs from context and write them to vault."""
        docs = self.generate_all(ctx, **kwargs)
        return self.write_docs(docs)
