"""
cortex.ide.base
---------------
Abstract base class for IDE adapters.

Every IDE adapter must implement this contract to provide
consistent profile injection, MCP configuration, and validation.
"""

from __future__ import annotations

import platform
import re
import shutil
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path
from typing import Any


def _generate_autogen_header(sources: list[str], ide_name: str) -> str:
    """Generate the autogeneration header for IDE config files.

    Args:
        sources: List of source files (e.g., [".cortex/skills/cortex-sync.md"])
        ide_name: Name of the IDE (e.g., "vscode")

    Returns:
        Formatted header string.
    """
    timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
    sources_str = ", ".join(sources)
    return f"""
⚠️ AUTOGENERATED BY CORTEX - DO NOT EDIT MANUALLY
Source: {sources_str}
Last sync: {timestamp}
Regenerate: cortex sync-ide --ide {ide_name} --force
"""


def _is_wsl() -> bool:
    """Detect if we are running under WSL."""
    if platform.system() != "Linux":
        return False
    try:
        version_content = Path("/proc/version").read_text().lower()
        return "microsoft" in version_content or "wsl" in version_content
    except Exception:
        return False


def _backup_file(file_path: Path) -> Path:
    """Create a timestamped backup of a file before modification.

    Args:
        file_path: Path to the file to backup.

    Returns:
        Path to the backup file.
    """
    if not file_path.exists():
        return file_path

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = file_path.parent / f"{file_path.name}.cortex_backup_{timestamp}"
    shutil.copy2(file_path, backup_path)
    return backup_path


def _deep_merge_dict(base: dict[str, Any], update: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge two dictionaries.

    Values from 'update' take precedence, but nested dicts are merged
    rather than replaced.

    Args:
        base: Original dictionary.
        update: Dictionary with updates to merge.

    Returns:
        Merged dictionary.
    """
    result = base.copy()
    for key, value in update.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge_dict(result[key], value)
        else:
            result[key] = value
    return result


def _append_to_markdown(file_path: Path, content: str, separator: str = "\n\n---\n\n") -> None:
    """Append content to a markdown file with a separator.

    If the file doesn't exist, it's created. If it exists, content is appended.

    Args:
        file_path: Path to the markdown file.
        content: Content to append.
        separator: Separator between existing and new content.
    """
    if file_path.exists():
        existing = file_path.read_text(encoding="utf-8")
        # Don't append if content already exists
        if content.strip() in existing:
            return
        file_path.write_text(existing + separator + content, encoding="utf-8")
    else:
        file_path.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Shared marker-block editing helpers (Obra 02 / Fase 1)
#
# Generalization of the BEGIN/END marker pattern pioneered by the Codex
# adapter (``cortex/ide/adapters/codex.py``). All adapters must stop
# reimplementing file-editing logic and reuse these pure helpers instead.
# They take and return strings only — no I/O — so callers keep full control
# over backup/write decisions.
# ---------------------------------------------------------------------------

#: Default markers (HTML-comment flavour used in Markdown files).
CORTEX_MARKER_OPEN = "<!-- BEGIN CORTEX SECTION (auto-generated, do not edit) -->"
CORTEX_MARKER_CLOSE = "<!-- END CORTEX SECTION -->"

# The sync timestamp inside the autogenerated header is the only part of a
# Cortex block that legitimately changes between runs; byte-equality checks
# ignore it.
_TIMESTAMP_LINE_RE = re.compile(r"^Last sync: .*$", re.MULTILINE)


def _marker_block_pattern(open_marker: str, close_marker: str) -> "re.Pattern[str]":
    """Compiled regex matching one full marker block (markers included)."""
    return re.compile(
        re.escape(open_marker) + r".*?" + re.escape(close_marker),
        re.DOTALL,
    )


def has_marker_block(
    content: str,
    open_marker: str = CORTEX_MARKER_OPEN,
    close_marker: str = CORTEX_MARKER_CLOSE,
) -> bool:
    """True if ``content`` contains at least one Cortex marker block."""
    return bool(_marker_block_pattern(open_marker, close_marker).search(content))


def extract_marker_blocks(
    content: str,
    open_marker: str = CORTEX_MARKER_OPEN,
    close_marker: str = CORTEX_MARKER_CLOSE,
) -> list[str]:
    """Return every Cortex block found in ``content``, markers included.

    Blocks are returned in order of appearance, verbatim (no whitespace
    normalization).
    """
    return [
        match.group(0)
        for match in _marker_block_pattern(open_marker, close_marker).finditer(content)
    ]


def strip_marker_blocks(
    content: str,
    open_marker: str = CORTEX_MARKER_OPEN,
    close_marker: str = CORTEX_MARKER_CLOSE,
) -> str:
    """Remove every Cortex block from ``content``, preserving everything else.

    Non-Cortex content is preserved byte-for-byte (trailing whitespace is only
    collapsed when at least one block was removed). If nothing but whitespace
    remains after removal, returns ``""`` so callers can decide to unlink the
    file instead of writing an empty one. Idempotent.
    """
    pattern = _marker_block_pattern(open_marker, close_marker)
    if not pattern.search(content):
        return content

    parts: list[str] = []
    last_end = 0
    for match in pattern.finditer(content):
        parts.append(content[last_end : match.start()])
        end = match.end()
        # Swallow the newline right after the block: avoids leaving a blank
        # line where the block used to be.
        if end < len(content) and content[end] == "\n":
            end += 1
        last_end = end
    parts.append(content[last_end:])
    cleaned = "".join(parts)

    if not cleaned.strip():
        return ""
    return cleaned.rstrip() + "\n"


def upsert_marker_block(
    content: str,
    block: str,
    open_marker: str = CORTEX_MARKER_OPEN,
    close_marker: str = CORTEX_MARKER_CLOSE,
) -> str:
    """Insert or replace the Cortex block in ``content`` (codex semantics).

    If a marked block already exists, everything between the FIRST open
    marker and the LAST close marker is replaced by ``block`` (stripped).
    Otherwise ``block`` is appended at the end with a separator that keeps
    existing content readable. Byte-idempotent: applying it twice yields the
    same string as applying it once.
    """
    block_body = block.strip()
    pattern = _marker_block_pattern(open_marker, close_marker)
    matches = list(pattern.finditer(content))
    if matches:
        first, last = matches[0], matches[-1]
        return content[: first.start()] + block_body + content[last.end() :]
    if not content:
        return block_body + "\n"
    sep = "\n" if content.endswith("\n") else "\n\n"
    return content + sep + block_body + "\n"


def is_cortex_owned_file(
    content: str,
    open_marker: str = CORTEX_MARKER_OPEN,
    close_marker: str = CORTEX_MARKER_CLOSE,
) -> bool:
    """True if Cortex created this file entirely.

    The safe-uninstall criterion: after stripping every marker block nothing
    but whitespace remains, so removing the blocks removes the whole file's
    meaning and the caller may unlink it. Files with any foreign content are
    NOT cortex-owned even if they contain a Cortex block.
    """
    if not content.strip():
        return False
    return strip_marker_blocks(content, open_marker, close_marker) == ""


def is_content_identical_to_bundle(
    content: str,
    bundle: str,
    *,
    ignore_timestamps: bool = True,
) -> bool:
    """True if ``content`` matches what Cortex would write (``bundle``).

    Comparison normalizes CRLF line endings, surrounding whitespace and — by
    default — the ``Last sync:`` timestamp line of the autogenerated header,
    which legitimately differs between runs.
    """

    def _normalize(text: str) -> str:
        text = text.replace("\r\n", "\n")
        if ignore_timestamps:
            text = _TIMESTAMP_LINE_RE.sub("Last sync: <timestamp>", text)
        return text.strip()

    return _normalize(content) == _normalize(bundle)


def _create_shielded_wrapper(project_root: Path) -> Path:
    """Create a shielded bash wrapper to filter WSL and Python noise.

    This protects the MCP JSON-RPC handshake from stderr pollution
    caused by WSL environment messages and Python warnings.
    """
    cortex_bin_dir = Path.home() / ".cortex" / "bin"
    cortex_log_dir = Path.home() / ".cortex" / "logs"
    cortex_bin_dir.mkdir(parents=True, exist_ok=True)
    cortex_log_dir.mkdir(parents=True, exist_ok=True)

    wrapper_path = cortex_bin_dir / "cortex-mcp-wrapper"
    log_file = cortex_log_dir / "mcp-shield.log"
    cortex_executable = shutil.which("cortex") or "cortex"

    wrapper_content = f"""#!/bin/bash
# Cortex Shielded Wrapper v3.0
# Intercepts WSL noise and redirects stderr to a dedicated log.

exec 2>> "{log_file}"

export PYTHONUNBUFFERED=1
export PYTHONIOENCODING=utf-8
export PYTHONWARNINGS=ignore

exec "{cortex_executable}" mcp-server --stdio --project-root "{project_root}"
"""
    wrapper_path.write_text(wrapper_content, encoding="utf-8")
    wrapper_path.chmod(0o755)
    return wrapper_path


class IDEAdapter(ABC):
    """Contract for all IDE adapters.

    Each adapter implements detection, profile injection, MCP setup,
    validation, and uninstallation for a specific IDE.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Machine-readable identifier (e.g. 'opencode', 'cursor')."""

    @property
    @abstractmethod
    def display_name(self) -> str:
        """Human-readable name (e.g. 'OpenCode', 'Cursor')."""

    @abstractmethod
    def get_config_paths(self) -> dict[str, Path]:
        """Return a dict of config path names to actual Paths.

        Example: {"config": Path("~/.config/opencode/opencode.json")}
        """

    @abstractmethod
    def inject_profiles(self, project_root: Path, prompts: dict[str, str]) -> list[str]:
        """Inject Cortex agent profiles in the IDE's native format.

        Args:
            project_root: Path to the Cortex project root.
            prompts: Dict of prompt_name -> prompt_content (e.g. 'cortex-sync' -> '...')

        Returns:
            List of files written/modified.
        """

    @abstractmethod
    def inject_mcp(self, project_root: Path) -> list[str]:
        """Inject MCP server configuration for the IDE.

        Args:
            project_root: Path to the Cortex project root.

        Returns:
            List of files written/modified.
        """

    def detect_installation(self) -> bool:
        """Detect if the IDE is installed on the system.

        Default implementation checks if any config path parent exists.
        Override for more specific detection.
        """
        return any(path.parent.exists() for path in self.get_config_paths().values())

    def validate(self) -> dict[str, bool]:
        """Validate that Cortex is correctly configured in this IDE.

        Returns:
            Dict of check_name -> passed (bool).
        """
        results: dict[str, bool] = {}
        for name, path in self.get_config_paths().items():
            results[f"{name}_exists"] = path.exists()
        return results

    def uninstall(self) -> list[str]:
        """Remove Cortex configuration from this IDE.

        Returns:
            List of files removed/cleaned.
        """
        removed: list[str] = []
        # Default: no-op. Override per-adapter for clean uninstall.
        return removed

    def needs_wsl_shielding(self) -> bool:
        """Whether this adapter requires WSL stderr shielding."""
        return False

    def _get_mcp_command(self, project_root: Path) -> dict[str, Any]:
        """Build the MCP server command definition.

        If running under WSL and the adapter requests shielding,
        uses the shielded wrapper. Otherwise, uses direct invocation.
        """
        if self.needs_wsl_shielding() and _is_wsl():
            wrapper = _create_shielded_wrapper(project_root)
            return {
                "command": str(wrapper),
                "args": [],
                "env": {},
            }
        return {
            "command": "cortex",
            "args": ["mcp-server", "--stdio"],
            "env": {
                "PYTHONPATH": str(project_root),
                "PYTHONWARNINGS": "ignore",
            },
        }

    def inject_all(self, project_root: Path, prompts: dict[str, str]) -> list[str]:
        """Convenience: inject both profiles and MCP in one call.

        Args:
            project_root: Path to the Cortex project root.
            prompts: Dict of prompt_name -> prompt_content.

        Returns:
            Combined list of files written/modified.
        """
        files: list[str] = []
        files.extend(self.inject_profiles(project_root, prompts))
        files.extend(self.inject_mcp(project_root))
        return files
