"""
cortex.ide.base
---------------
Abstract base class for IDE adapters.

Every IDE adapter must implement this contract to provide
consistent profile injection, MCP configuration, and validation.
"""

from __future__ import annotations

import platform
import shutil
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path
from typing import Any


def _generate_autogen_header(sources: list[str], ide_name: str) -> str:
    """Generate the autogeneration header for IDE config files.

    Args:
        sources: List of source files (e.g., [".cortex/skills/cortex-sync.md"])
        ide_name: Name of the IDE (e.g., "vscode")

    Returns:
        Formatted header string.
    """
    timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
    sources_str = ", ".join(sources)
    return f"""
⚠️ AUTOGENERATED BY CORTEX - DO NOT EDIT MANUALLY
Source: {sources_str}
Last sync: {timestamp}
Regenerate: cortex sync-ide --ide {ide_name} --force
"""


def _is_wsl() -> bool:
    """Detect if we are running under WSL."""
    if platform.system() != "Linux":
        return False
    try:
        version_content = Path("/proc/version").read_text().lower()
        return "microsoft" in version_content or "wsl" in version_content
    except Exception:
        return False


def _backup_file(file_path: Path) -> Path:
    """Create a timestamped backup of a file before modification.

    Args:
        file_path: Path to the file to backup.

    Returns:
        Path to the backup file.
    """
    if not file_path.exists():
        return file_path

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = file_path.parent / f"{file_path.name}.cortex_backup_{timestamp}"
    shutil.copy2(file_path, backup_path)
    return backup_path


def _deep_merge_dict(base: dict[str, Any], update: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge two dictionaries.

    Values from 'update' take precedence, but nested dicts are merged
    rather than replaced.

    Args:
        base: Original dictionary.
        update: Dictionary with updates to merge.

    Returns:
        Merged dictionary.
    """
    result = base.copy()
    for key, value in update.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge_dict(result[key], value)
        else:
            result[key] = value
    return result


def _append_to_markdown(file_path: Path, content: str, separator: str = "\n\n---\n\n") -> None:
    """Append content to a markdown file with a separator.

    If the file doesn't exist, it's created. If it exists, content is appended.

    Args:
        file_path: Path to the markdown file.
        content: Content to append.
        separator: Separator between existing and new content.
    """
    if file_path.exists():
        existing = file_path.read_text(encoding="utf-8")
        # Don't append if content already exists
        if content.strip() in existing:
            return
        file_path.write_text(existing + separator + content, encoding="utf-8")
    else:
        file_path.write_text(content, encoding="utf-8")


def _create_shielded_wrapper(project_root: Path) -> Path:
    """Create a shielded bash wrapper to filter WSL and Python noise.

    This protects the MCP JSON-RPC handshake from stderr pollution
    caused by WSL environment messages and Python warnings.
    """
    cortex_bin_dir = Path.home() / ".cortex" / "bin"
    cortex_log_dir = Path.home() / ".cortex" / "logs"
    cortex_bin_dir.mkdir(parents=True, exist_ok=True)
    cortex_log_dir.mkdir(parents=True, exist_ok=True)

    wrapper_path = cortex_bin_dir / "cortex-mcp-wrapper"
    log_file = cortex_log_dir / "mcp-shield.log"

    wrapper_content = f"""#!/bin/bash
# Cortex Shielded Wrapper v3.0
# Intercepts WSL noise and redirects stderr to a dedicated log.

exec 2>> "{log_file}"

export PYTHONUNBUFFERED=1
export PYTHONIOENCODING=utf-8
export PYTHONWARNINGS=ignore
export PYTHONPATH="{project_root}"

set -m

exec /usr/bin/python3 -m cortex.cli.main mcp-server --stdio
"""
    wrapper_path.write_text(wrapper_content, encoding="utf-8")
    wrapper_path.chmod(0o755)
    return wrapper_path


class IDEAdapter(ABC):
    """Contract for all IDE adapters.

    Each adapter implements detection, profile injection, MCP setup,
    validation, and uninstallation for a specific IDE.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Machine-readable identifier (e.g. 'opencode', 'cursor')."""

    @property
    @abstractmethod
    def display_name(self) -> str:
        """Human-readable name (e.g. 'OpenCode', 'Cursor')."""

    @abstractmethod
    def get_config_paths(self) -> dict[str, Path]:
        """Return a dict of config path names to actual Paths.

        Example: {"config": Path("~/.config/opencode/opencode.json")}
        """

    @abstractmethod
    def inject_profiles(self, project_root: Path, prompts: dict[str, str]) -> list[str]:
        """Inject Cortex agent profiles in the IDE's native format.

        Args:
            project_root: Path to the Cortex project root.
            prompts: Dict of prompt_name -> prompt_content (e.g. 'cortex-sync' -> '...')

        Returns:
            List of files written/modified.
        """

    @abstractmethod
    def inject_mcp(self, project_root: Path) -> list[str]:
        """Inject MCP server configuration for the IDE.

        Args:
            project_root: Path to the Cortex project root.

        Returns:
            List of files written/modified.
        """

    def detect_installation(self) -> bool:
        """Detect if the IDE is installed on the system.

        Default implementation checks if any config path parent exists.
        Override for more specific detection.
        """
        return any(path.parent.exists() for path in self.get_config_paths().values())

    def validate(self) -> dict[str, bool]:
        """Validate that Cortex is correctly configured in this IDE.

        Returns:
            Dict of check_name -> passed (bool).
        """
        results: dict[str, bool] = {}
        for name, path in self.get_config_paths().items():
            results[f"{name}_exists"] = path.exists()
        return results

    def uninstall(self) -> list[str]:
        """Remove Cortex configuration from this IDE.

        Returns:
            List of files removed/cleaned.
        """
        removed: list[str] = []
        # Default: no-op. Override per-adapter for clean uninstall.
        return removed

    def needs_wsl_shielding(self) -> bool:
        """Whether this adapter requires WSL stderr shielding."""
        return False

    def _get_mcp_command(self, project_root: Path) -> dict[str, Any]:
        """Build the MCP server command definition.

        If running under WSL and the adapter requests shielding,
        uses the shielded wrapper. Otherwise, uses direct invocation.
        """
        if self.needs_wsl_shielding() and _is_wsl():
            wrapper = _create_shielded_wrapper(project_root)
            return {
                "command": str(wrapper),
                "args": [],
                "env": {},
            }
        return {
            "command": "cortex",
            "args": ["mcp-server", "--stdio"],
            "env": {
                "PYTHONPATH": str(project_root),
                "PYTHONWARNINGS": "ignore",
            },
        }

    def inject_all(self, project_root: Path, prompts: dict[str, str]) -> list[str]:
        """Convenience: inject both profiles and MCP in one call.

        Args:
            project_root: Path to the Cortex project root.
            prompts: Dict of prompt_name -> prompt_content.

        Returns:
            Combined list of files written/modified.
        """
        files: list[str] = []
        files.extend(self.inject_profiles(project_root, prompts))
        files.extend(self.inject_mcp(project_root))
        return files
