//! Puerto de `cortex/ci/markdown_formatter.py` — comentario de PR (L2).
//!
//! Salida delimitada por un marcador sentinela para que el workflow pueda
//! de-duplicar en re-runs (`gh pr comment --edit-last`). El marcador es
//! exacto y estable entre releases.

use crate::ci::result::ValidationResult;

pub const DEFAULT_MARKER: &str = "<!-- cortex-pr-summary -->";

/// Formatear un bloque Markdown listo para postear como comentario de PR.
pub fn render_pr_comment(result: &ValidationResult, marker: &str) -> String {
    let mut lines: Vec<String> = vec![marker.to_string()];
    let title = title_of(result);
    lines.push(format!("### {title}"));
    lines.push(String::new());

    lines.push(format!(
        "**Status:** {} · {} blocker(s) · {} warning(s)",
        status_upper(result),
        result.blockers.len(),
        result.warnings.len()
    ));
    lines.push(String::new());

    match &result.matched_session {
        None => {
            lines.push(
                "_No Cortex Session matched this PR. Open one with_ \
                 `cortex create-spec ...` _before re-running CI._"
                    .to_string(),
            );
            lines.push(String::new());
        }
        Some(session) => {
            lines.push(format!("**Session:** `{}`", session.session_id));
            if let Some(spec) = &result.spec {
                lines.push(format!("**Spec:** `{}`", spec.path.to_string_lossy()));
            }
            lines.push(format!("**Match:** `{}`", result.session_match.as_str()));
            lines.push(String::new());

            lines.extend(render_files_section(result));
            lines.extend(render_hooks_section(result));
            lines.extend(render_scope_drift_section(&result.scope_drift));
        }
    }

    if !result.blockers.is_empty() {
        lines.push("#### Blockers".into());
        for b in &result.blockers {
            lines.push(format!("- {b}"));
        }
        lines.push(String::new());
    }

    if !result.warnings.is_empty() {
        lines.push("#### Warnings".into());
        for w in &result.warnings {
            lines.push(format!("- {w}"));
        }
        lines.push(String::new());
    }

    lines.push("<sub>Generated by Cortex CI. Re-run the workflow to refresh.</sub>".into());
    lines.push(marker.to_string());
    lines.join("\n") + "\n"
}

fn status_upper(result: &ValidationResult) -> String {
    // Python: result.status.upper() — pass/warn/blocked/error.
    result.status.as_str().to_ascii_uppercase()
}

fn title_of(result: &ValidationResult) -> String {
    if let Some(session) = &result.matched_session {
        return format!("Cortex PR validation · `{}`", session.session_id);
    }
    if let Some(n) = result.pr_number {
        return format!("Cortex PR validation · PR #{n}");
    }
    "Cortex PR validation".to_string()
}

fn render_files_section(result: &ValidationResult) -> Vec<String> {
    if result.files_in_diff.is_empty() {
        return vec!["_No files in diff._".into(), String::new()];
    }
    let mut out = vec!["#### Files in diff".to_string()];
    let visible: Vec<_> = result.files_in_diff.iter().take(10).collect();
    for path in visible {
        out.push(format!("- `{}`", path.to_string_lossy()));
    }
    let extra = result.files_in_diff.len() - result.files_in_diff.len().min(10);
    if extra > 0 {
        out.push(format!("- _(…and {extra} more)_"));
    }
    out.push(String::new());
    out
}

fn render_hooks_section(result: &ValidationResult) -> Vec<String> {
    if result.verification_results.is_empty() {
        return vec![
            "_No verification hooks declared in the spec — validation is partial._".into(),
            String::new(),
        ];
    }
    let mut out = vec!["#### Verification hooks".to_string()];
    for r in &result.verification_results {
        let marker = if r.passed { "✓" } else { "✗" };
        let duration = format!("{:.1}", r.duration_ms as f64 / 1000.0);
        out.push(format!(
            "- {marker} `{}` ({duration}s, exit {})",
            r.name, r.exit_code
        ));
    }
    out.push(String::new());
    out
}

fn render_scope_drift_section(drift: &[crate::ci::result::ScopeDriftFinding]) -> Vec<String> {
    if drift.is_empty() {
        return vec![];
    }
    let mut out = vec!["#### Scope drift".to_string()];
    for finding in drift {
        out.push(format!(
            "- `{}` — {}",
            finding.path.to_string_lossy(),
            finding.reason.as_str()
        ));
    }
    out.push(String::new());
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ci::result::{DriftReason, ScopeDriftFinding, ValidationStatus};
    use crate::session::service::SessionMatchKind;
    use crate::session::{SessionRecord, VerificationHookResult};

    fn session() -> SessionRecord {
        SessionRecord {
            session_id: "2026-05-17_demo".into(),
            spec_path: "vault/specs/demo.md".into(),
            spec_summary: "demo".into(),
            start_commit: "a".repeat(40),
            start_branch: "feature/demo".into(),
            opened_at: crate::session::service::now_iso(),
            ..Default::default()
        }
    }

    fn base_result() -> ValidationResult {
        ValidationResult {
            session_match: SessionMatchKind::Explicit,
            matched_session: Some(session()),
            spec: None,
            files_in_diff: vec!["src/x.py".into()],
            scope_drift: vec![],
            verification_results: vec![],
            blockers: vec![],
            warnings: vec![],
            exit_code: 0,
            status: ValidationStatus::Pass,
            summary_text: "session=2026-05-17_demo status=pass".into(),
            pr_number: Some(42),
            pr_author: None,
            head_branch: None,
        }
    }

    #[test]
    fn marcador_y_formato_pass() {
        let text = render_pr_comment(&base_result(), DEFAULT_MARKER);
        assert!(text.starts_with(DEFAULT_MARKER));
        assert!(text.trim_end().ends_with(DEFAULT_MARKER));
        assert!(text.contains("PASS"));
        assert!(text.contains("0 blocker(s)"));
        assert!(text.contains("### Cortex PR validation · `2026-05-17_demo`"));
        assert!(text.ends_with("\n"));
    }

    #[test]
    fn secciones_files_hooks_drift() {
        let mut r = base_result();
        r.verification_results = vec![
            VerificationHookResult {
                name: "tests".into(),
                command: "true".into(),
                passed: true,
                exit_code: 0,
                output: String::new(),
                duration_ms: 1200,
                run_at: crate::session::service::now_iso(),
            },
            VerificationHookResult {
                name: "lint".into(),
                command: "false".into(),
                passed: false,
                exit_code: 1,
                output: String::new(),
                duration_ms: 300,
                run_at: crate::session::service::now_iso(),
            },
        ];
        r.scope_drift = vec![ScopeDriftFinding {
            path: "src/y.py".into(),
            reason: DriftReason::OutOfScope,
        }];
        let text = render_pr_comment(&r, DEFAULT_MARKER);
        assert!(text.contains("#### Files in diff"));
        assert!(text.contains("- `src/x.py`"));
        assert!(text.contains("- ✓ `tests` (1.2s, exit 0)"));
        assert!(text.contains("- ✗ `lint` (0.3s, exit 1)"));
        assert!(text.contains("#### Scope drift"));
        assert!(text.contains("- `src/y.py` — out_of_scope"));

        // Sin hooks ⇒ nota de validación parcial.
        let r2 = base_result();
        let t2 = render_pr_comment(&r2, DEFAULT_MARKER);
        assert!(t2.contains("validation is partial"));
    }

    #[test]
    fn truncado_de_archivos_y_titulo_fallback() {
        let mut r = base_result();
        r.files_in_diff = (0..12).map(|i| format!("f{i}.py").into()).collect();
        let text = render_pr_comment(&r, DEFAULT_MARKER);
        assert!(text.contains("_(…and 2 more)_"));

        // Sin sesión y con pr_number ⇒ título por PR.
        let mut r2 = base_result();
        r2.matched_session = None;
        r2.pr_number = Some(7);
        let t2 = render_pr_comment(&r2, DEFAULT_MARKER);
        assert!(t2.contains("### Cortex PR validation · PR #7"));
        assert!(t2.contains("_No Cortex Session matched this PR."));

        // Sin nada ⇒ título genérico.
        let mut r3 = base_result();
        r3.matched_session = None;
        r3.pr_number = None;
        let t3 = render_pr_comment(&r3, DEFAULT_MARKER);
        assert!(t3.contains("### Cortex PR validation\n"));
    }
}
