"""cortex.ci.markdown_formatter — Render a ``ValidationResult`` as Markdown
for the Level 2 PR comment workflow.

The output is delimited by a sentinel marker so the workflow can
de-duplicate on re-runs (``gh pr comment --edit-last`` or equivalent).
The marker is exact and stable across releases.
"""

from __future__ import annotations

from cortex.ci.result import ScopeDriftFinding, ValidationResult

DEFAULT_MARKER = "<!-- cortex-pr-summary -->"


def render_pr_comment(
    result: ValidationResult,
    *,
    marker: str = DEFAULT_MARKER,
) -> str:
    """Format a Markdown block ready to post as a PR comment."""
    lines: list[str] = [marker]
    title = _title(result)
    lines.append(f"### {title}")
    lines.append("")

    lines.append(
        f"**Status:** {result.status.upper()} · "
        f"{len(result.blockers)} blocker(s) · "
        f"{len(result.warnings)} warning(s)"
    )
    lines.append("")

    if result.matched_session is None:
        lines.append(
            "_No Cortex Session matched this PR. Open one with_ "
            "`cortex create-spec ...` _before re-running CI._"
        )
        lines.append("")
    else:
        lines.append(f"**Session:** `{result.matched_session.session_id}`")
        if result.spec is not None:
            lines.append(f"**Spec:** `{result.spec.path}`")
        lines.append(f"**Match:** `{result.session_match}`")
        lines.append("")

        lines.extend(_render_files_section(result))
        lines.extend(_render_hooks_section(result))
        lines.extend(_render_scope_drift_section(result.scope_drift))

    if result.blockers:
        lines.append("#### Blockers")
        for b in result.blockers:
            lines.append(f"- {b}")
        lines.append("")

    if result.warnings:
        lines.append("#### Warnings")
        for w in result.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("<sub>Generated by Cortex CI. Re-run the workflow to refresh.</sub>")
    lines.append(marker)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _title(result: ValidationResult) -> str:
    if result.matched_session is not None:
        return f"Cortex PR validation · `{result.matched_session.session_id}`"
    if result.pr_number is not None:
        return f"Cortex PR validation · PR #{result.pr_number}"
    return "Cortex PR validation"


def _render_files_section(result: ValidationResult) -> list[str]:
    if not result.files_in_diff:
        return ["_No files in diff._", ""]
    out = ["#### Files in diff"]
    visible = result.files_in_diff[:10]
    for path in visible:
        out.append(f"- `{path.as_posix()}`")
    extra = len(result.files_in_diff) - len(visible)
    if extra > 0:
        out.append(f"- _(…and {extra} more)_")
    out.append("")
    return out


def _render_hooks_section(result: ValidationResult) -> list[str]:
    if not result.verification_results:
        return [
            "_No verification hooks declared in the spec — validation is partial._",
            "",
        ]
    out = ["#### Verification hooks"]
    for r in result.verification_results:
        marker = "✓" if r.passed else "✗"
        duration = f"{r.duration_ms / 1000:.1f}s"
        out.append(f"- {marker} `{r.name}` ({duration}, exit {r.exit_code})")
    out.append("")
    return out


def _render_scope_drift_section(drift: list[ScopeDriftFinding]) -> list[str]:
    if not drift:
        return []
    out = ["#### Scope drift"]
    for finding in drift:
        out.append(f"- `{finding.path.as_posix()}` — {finding.reason}")
    out.append("")
    return out


__all__ = ["DEFAULT_MARKER", "render_pr_comment"]
