//! Puerto de `cortex.doc_generator` (P12A-4): generador FALLBACK de docs.
//!
//! Espeja tests/unit/pr/test_pr_context.py (TestDocGenerator). El template se
//! renderiza con replace simple + regex `\{\{[^}]*\}\}` → "N/A" (NO es jinja,
//! igual que Python).
//!
//! Divergencias documentadas:
//! - El reloj es explícito (`now`) para filename y contenido: Python usa
//!   `datetime.now(UTC)`; los writers nativos ya hacen explícito el tiempo.

use std::path::PathBuf;

use chrono::{DateTime, Utc};
use regex::RegexBuilder;

/// Puerto de `models.GeneratedDoc`.
#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedDoc {
    pub doc_type: DocTypeGen,
    pub title: String,
    pub content: String,
    pub vault_subfolder: String,
    pub filename: String,
}

/// Literal["session","hu","adr","incident","changelog","security"].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DocTypeGen {
    Session,
    Hu,
    Adr,
    Incident,
    Changelog,
    Security,
}

impl DocTypeGen {
    pub fn value(self) -> &'static str {
        match self {
            Self::Session => "session",
            Self::Hu => "hu",
            Self::Adr => "adr",
            Self::Incident => "incident",
            Self::Changelog => "changelog",
            Self::Security => "security",
        }
    }
}

const TEMPLATE_SESSION: &str = "\
---
title: \"{{title}}\"
date: {{date}}
pr: \"#{{pr_number}}\"
author: {{author}}
branch: {{source_branch}}
commit: {{commit_sha}}
tags: [session{{tags}}]
status: fallback
---
# {{title}}

> [!warning] Fallback Documentation
> This note was auto-generated by Cortex because no agent-written
> documentation was found in this PR. Consider writing proper docs
> next time using your AI agent's Obsidian Markdown skills.

## Summary
{{body_summary}}

## Changes
{{diff_summary}}

## Pipeline Results
| Check | Result |
|-------|--------|
| Lint (SAST) | {{lint_result}} |
| Audit (SCA) | {{audit_result}} |
| Tests | {{test_result}} |

## Files Modified
{{files_list}}
";

pub struct DocGenerator {
    pub vault_path: PathBuf,
}

impl DocGenerator {
    pub fn new(vault_path: impl Into<PathBuf>) -> Self {
        Self {
            vault_path: vault_path.into(),
        }
    }

    /// `_safe_filename`: lower/strip → quitar [^\w\s-] → colapsar \s+ → "-" →
    /// cap 80 → `{today}_{name}.md` o `{today}.md`.
    pub fn safe_filename(&self, title: &str, today: &str) -> String {
        let re_strip = RegexBuilder::new(r"[^\w\s-]").build().expect("regex");
        let lowered = title.trim().to_lowercase();
        let mut name: String = re_strip.replace_all(&lowered, "").into_owned();
        let re_space = RegexBuilder::new(r"[\s]+").build().expect("regex");
        name = re_space.replace_all(&name, "-").into_owned();
        // Cap de 80 caracteres por límite de BYTES de char boundary seguro.
        let mut cut = 80.min(name.len());
        while !name.is_char_boundary(cut) {
            cut -= 1;
        }
        name.truncate(cut);
        if name.is_empty() {
            format!("{today}.md")
        } else {
            format!("{today}_{name}.md")
        }
    }

    /// `_render`: replace de `{{key}}` por valor; placeholders restantes ⇒ N/A.
    fn render(template: &str, kwargs: &[(&str, String)]) -> String {
        let mut result = template.to_string();
        for (key, value) in kwargs {
            result = result.replace(&format!("{{{{{key}}}}}"), value);
        }
        let re_na = RegexBuilder::new(r"\{\{[^}]*\}\}").build().expect("regex");
        re_na.replace_all(&result, "N/A").into_owned()
    }

    /// `generate_session`. `now` alimenta date/filename (divergencia doc).
    pub fn generate_session(&self, ctx: &crate::pr::PRContext, now: DateTime<Utc>) -> GeneratedDoc {
        let body_summary: String = if ctx.body.is_empty() {
            "No description provided.".to_string()
        } else {
            ctx.body.chars().take(300).collect()
        };
        let mut files_list = ctx
            .files_changed
            .iter()
            .take(20)
            .map(|f| format!("- `{f}`"))
            .collect::<Vec<_>>()
            .join("\n");
        if files_list.is_empty() {
            files_list = "- (none)".to_string();
        }
        let tags = if ctx.labels.is_empty() {
            String::new()
        } else {
            ctx.labels
                .iter()
                .take(5)
                .map(|l| format!(", {l}"))
                .collect()
        };
        let today = now.format("%Y-%m-%d").to_string();
        let commit8: String = ctx.commit_sha.chars().take(8).collect();
        let lint = ctx.lint_result.clone().unwrap_or_else(|| "not run".into());
        let audit = ctx.audit_result.clone().unwrap_or_else(|| "not run".into());
        let test = ctx.test_result.clone().unwrap_or_else(|| "not run".into());
        let diff = if ctx.diff_summary.is_empty() {
            "(no diff summary)".to_string()
        } else {
            ctx.diff_summary.clone()
        };

        let content = Self::render(
            TEMPLATE_SESSION,
            &[
                ("title", ctx.title.clone()),
                ("date", today.clone()),
                ("pr_number", ctx.pr_number.to_string()),
                ("author", ctx.author.clone()),
                ("source_branch", ctx.source_branch.clone()),
                ("commit_sha", commit8),
                ("tags", tags),
                ("body_summary", body_summary),
                ("diff_summary", diff),
                ("lint_result", lint),
                ("audit_result", audit),
                ("test_result", test),
                ("files_list", files_list),
            ],
        );

        GeneratedDoc {
            doc_type: DocTypeGen::Session,
            title: ctx.title.clone(),
            content,
            vault_subfolder: "sessions".to_string(),
            filename: self.safe_filename(&ctx.title, &today),
        }
    }

    /// `generate_all`: sólo session en modo fallback.
    pub fn generate_all(
        &self,
        ctx: &crate::pr::PRContext,
        now: DateTime<Utc>,
        skip_types: &[&str],
    ) -> Vec<GeneratedDoc> {
        let mut docs = Vec::new();
        if !skip_types.contains(&"session") {
            docs.push(self.generate_session(ctx, now));
        }
        docs
    }

    /// `write_docs`.
    pub fn write_docs(&self, docs: &[GeneratedDoc]) -> Result<Vec<PathBuf>, String> {
        let mut written = Vec::new();
        for doc in docs {
            let target_dir = self.vault_path.join(&doc.vault_subfolder);
            std::fs::create_dir_all(&target_dir).map_err(|e| e.to_string())?;
            let target_file = target_dir.join(&doc.filename);
            std::fs::write(&target_file, &doc.content).map_err(|e| e.to_string())?;
            written.push(target_file);
        }
        Ok(written)
    }

    /// `generate_and_write`.
    pub fn generate_and_write(
        &self,
        ctx: &crate::pr::PRContext,
        now: DateTime<Utc>,
        skip_types: &[&str],
    ) -> Result<Vec<PathBuf>, String> {
        let docs = self.generate_all(ctx, now, skip_types);
        self.write_docs(&docs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixed_now() -> DateTime<Utc> {
        chrono::TimeZone::with_ymd_and_hms(&Utc, 2026, 6, 1, 12, 0, 0).unwrap()
    }

    #[test]
    fn safe_filename_basico_y_edge() {
        let gen = DocGenerator::new("vault");
        let name = gen.safe_filename("Fix login bug! @#$%", "2026-06-01");
        assert!(name.ends_with(".md"));
        assert!(name.contains("fix-login-bug"), "{name}");
        assert!(!name.contains('!'));
        assert!(!name.contains('@'));
        // Sólo símbolos ⇒ nombre vacío ⇒ "{today}.md"
        assert_eq!(gen.safe_filename("***", "2026-06-01"), "2026-06-01.md");
    }

    #[test]
    fn fallback_genera_session_con_warning() {
        let tmp = std::env::temp_dir().join(format!("dg_a_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let gen = DocGenerator::new(&tmp);
        let ctx = crate::pr::PRContext {
            title: "Fallback test".into(),
            body: "Testing fallback mode.".into(),
            author: "dev1".into(),
            source_branch: "fix/login".into(),
            commit_sha: "abc123def456".into(),
            pr_number: 42,
            ..Default::default()
        };
        let doc = gen.generate_session(&ctx, fixed_now());
        assert_eq!(doc.doc_type.value(), "session");
        assert_eq!(doc.vault_subfolder, "sessions");
        assert!(doc.content.contains("Fallback test"));
        assert!(doc.content.contains("dev1"));
        assert!(doc.content.contains("abc123de")); // commit_sha[:8]
        assert!(doc.content.to_lowercase().contains("fallback"));
        assert!(doc.content.contains("[!warning]"));
        assert_eq!(doc.filename, "2026-06-01_fallback-test.md");

        let docs = gen.generate_all(&ctx, fixed_now(), &[]);
        assert_eq!(docs.len(), 1);
        let written = gen.write_docs(&docs).unwrap();
        assert_eq!(written.len(), 1);
        assert!(written[0].exists());
        assert!(!std::fs::read_to_string(&written[0])
            .unwrap()
            .trim()
            .is_empty());
        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn pipeline_results_y_defaults() {
        let gen = DocGenerator::new("vault");
        let ctx = crate::pr::PRContext {
            title: "Fix login bug".into(),
            body: "refresh".into(),
            author: "dev1".into(),
            source_branch: "fix/x".into(),
            commit_sha: "abc123def456".into(),
            lint_result: Some("pass".into()),
            audit_result: Some("pass".into()),
            test_result: Some("pass".into()),
            diff_summary: " a.py | 1 +".into(),
            files_changed: vec!["a.py".into()],
            ..Default::default()
        };
        let doc = gen.generate_session(&ctx, fixed_now());
        assert!(doc.content.contains("| Lint (SAST) | pass |"));
        assert!(doc.content.contains("| Audit (SCA) | pass |"));
        assert!(doc.content.contains("- `a.py`"));

        let vacio = crate::pr::PRContext {
            title: "T".into(),
            author: "a".into(),
            source_branch: "b".into(),
            commit_sha: "c".into(),
            ..Default::default()
        };
        let d2 = gen.generate_session(&vacio, fixed_now());
        assert!(d2.content.contains("No description provided."));
        assert!(d2.content.contains("(no diff summary)"));
        assert!(d2.content.contains("| Lint (SAST) | not run |"));
        assert!(d2.content.contains("- (none)"));
    }
}
