//! Porteo de `cortex/ide/base.py` — helpers compartidos de los adapters.
//!
//! Fidelidad byte-a-byte: headers, marker blocks y JSON dumps idénticos.

use std::path::{Path, PathBuf};

use serde_json::Value;

use super::IdeCtx;

pub const CORTEX_MARKER_OPEN: &str = "<!-- BEGIN CORTEX SECTION (auto-generated, do not edit) -->";
pub const CORTEX_MARKER_CLOSE: &str = "<!-- END CORTEX SECTION -->";

/// `_generate_autogen_header`: el string empieza con `\n` igual que Python.
pub fn generate_autogen_header(ctx: &IdeCtx, sources: &[&str], ide_name: &str) -> String {
    // datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ") en hora LOCAL del
    // proceso; los fixtures congelan `now` ya en hora local deseada.
    let timestamp = ctx.now.format("%Y-%m-%dT%H:%M:%SZ");
    let sources_str = sources.join(", ");
    format!(
        "\n⚠️ AUTOGENERATED BY CORTEX - DO NOT EDIT MANUALLY\n\
         Source: {sources_str}\n\
         Last sync: {timestamp}\n\
         Regenerate: cortex sync-ide --ide {ide_name} --force\n"
    )
}

/// `_backup_file`: copia `<name>.cortex_backup_%Y%m%d_%H%M%S` si existe.
/// Devuelve la ruta de backup (o la original si no había nada que respaldar).
pub fn backup_file(ctx: &IdeCtx, file_path: &Path) -> PathBuf {
    if !file_path.exists() {
        return file_path.to_path_buf();
    }
    let timestamp = ctx.now.format("%Y%m%d_%H%M%S");
    let name = file_path.file_name().unwrap_or_default().to_string_lossy();
    let backup = file_path
        .parent()
        .unwrap_or(Path::new("."))
        .join(format!("{name}.cortex_backup_{timestamp}"));
    let _ = std::fs::copy(file_path, &backup);
    backup
}

/// `_deep_merge_dict` sobre serde_json Values (solo objetos se fusionan).
pub fn deep_merge_dict(base: &Value, update: &Value) -> Value {
    match (base, update) {
        (Value::Object(b), Value::Object(u)) => {
            let mut result = b.clone();
            for (k, v) in u {
                match result.get(k) {
                    Some(existing) if existing.is_object() && v.is_object() => {
                        result.insert(k.clone(), deep_merge_dict(existing, v));
                    }
                    _ => {
                        result.insert(k.clone(), v.clone());
                    }
                }
            }
            Value::Object(result)
        }
        (_, update) => update.clone(),
    }
}

/// `_append_to_markdown`.
pub fn append_to_markdown(file_path: &Path, content: &str, separator: &str) -> std::io::Result<()> {
    if file_path.exists() {
        let existing = std::fs::read_to_string(file_path)?;
        if existing.contains(content.trim()) {
            return Ok(());
        }
        std::fs::write(file_path, format!("{existing}{separator}{content}"))
    } else {
        std::fs::write(file_path, content)
    }
}

// ---------------------------------------------------------------------------
// Marker block helpers (Obra 02 / Fase 1)
// ---------------------------------------------------------------------------

/// True si `content` contiene al menos un bloque entre marcadores.
pub fn has_marker_block(content: &str) -> bool {
    has_marker_block_with(content, CORTEX_MARKER_OPEN, CORTEX_MARKER_CLOSE)
}

pub fn has_marker_block_with(content: &str, open_marker: &str, close_marker: &str) -> bool {
    find_block(content, open_marker, close_marker).is_some()
}

struct Block {
    start: usize,
    end: usize,
}

/// Primer bloque completo (bytes), marcadores incluidos.
fn find_block(haystack: &str, open_marker: &str, close_marker: &str) -> Option<Block> {
    let bytes = haystack.as_bytes();
    let open_b = open_marker.as_bytes();
    let close_b = close_marker.as_bytes();
    let mut i = 0;
    while i + open_b.len() <= bytes.len() {
        if &bytes[i..i + open_b.len()] == open_b {
            let mut j = i + open_b.len();
            while j + close_b.len() <= bytes.len() {
                if &bytes[j..j + close_b.len()] == close_b {
                    return Some(Block {
                        start: i,
                        end: j + close_b.len(),
                    });
                }
                j += 1;
            }
            return None; // abierto sin cerrar
        }
        i += 1;
    }
    None
}

/// Todos los bloques verbatim (marcadores incluidos), en orden.
pub fn extract_marker_blocks(content: &str) -> Vec<String> {
    extract_marker_blocks_with(content, CORTEX_MARKER_OPEN, CORTEX_MARKER_CLOSE)
}

pub fn extract_marker_blocks_with(
    content: &str,
    open_marker: &str,
    close_marker: &str,
) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = content;
    let mut offset = 0usize;
    while let Some(b) = find_block(rest, open_marker, close_marker) {
        out.push(rest[b.start..b.end].to_string());
        offset += b.end;
        rest = &content[offset..];
    }
    out
}

/// `strip_marker_blocks`: elimina bloques preservando el resto byte-a-byte;
/// colapsa whitespace final sólo si removió algo. Idempotente.
pub fn strip_marker_blocks(content: &str) -> String {
    strip_marker_blocks_with(content, CORTEX_MARKER_OPEN, CORTEX_MARKER_CLOSE)
}

pub fn strip_marker_blocks_with(content: &str, open_marker: &str, close_marker: &str) -> String {
    if find_block(content, open_marker, close_marker).is_none() {
        return content.to_string();
    }
    let mut parts: Vec<&str> = Vec::new();
    let mut rest = content;
    loop {
        match find_block(rest, open_marker, close_marker) {
            None => {
                parts.push(rest);
                break;
            }
            Some(b) => {
                parts.push(&rest[..b.start]);
                let mut end = b.end;
                let bytes = rest.as_bytes();
                if end < bytes.len() && bytes[end] == b'\n' {
                    end += 1;
                }
                rest = &rest[end..];
            }
        }
    }
    let cleaned: String = parts.concat();
    if cleaned.trim().is_empty() {
        return String::new();
    }
    cleaned.trim_end().to_string() + "\n"
}

/// `upsert_marker_block` (semántica codex).
pub fn upsert_marker_block(content: &str, block: &str) -> String {
    upsert_marker_block_with(content, block, CORTEX_MARKER_OPEN, CORTEX_MARKER_CLOSE)
}

pub fn upsert_marker_block_with(
    content: &str,
    block: &str,
    open_marker: &str,
    close_marker: &str,
) -> String {
    let block_body = block.trim();
    let matches: Vec<Block> = {
        let mut v = Vec::new();
        let mut rest_offset = 0usize;
        let mut rest = content;
        while let Some(b) = find_block(rest, open_marker, close_marker) {
            v.push(Block {
                start: rest_offset + b.start,
                end: rest_offset + b.end,
            });
            rest_offset += b.end;
            rest = &content[rest_offset..];
        }
        v
    };
    if let (Some(first), Some(last)) = (matches.first(), matches.last()) {
        return format!(
            "{}{}{}",
            &content[..first.start],
            block_body,
            &content[last.end..]
        );
    }
    if content.is_empty() {
        return format!("{block_body}\n");
    }
    let sep = if content.ends_with('\n') {
        "\n"
    } else {
        "\n\n"
    };
    format!("{content}{sep}{block_body}\n")
}

/// `is_cortex_owned_file`.
pub fn is_cortex_owned_file(content: &str) -> bool {
    if content.trim().is_empty() {
        return false;
    }
    strip_marker_blocks(content).is_empty()
}

/// `is_content_identical_to_bundle` con normalización de CRLF + timestamps.
pub fn is_content_identical_to_bundle(content: &str, bundle: &str) -> bool {
    normalize_for_compare(content) == normalize_for_compare(bundle)
}

fn normalize_for_compare(text: &str) -> String {
    let no_crlf = text.replace("\r\n", "\n");
    // ^Last sync: .*$ → "Last sync: <timestamp>" (línea por línea).
    let mut normalized_lines: Vec<String> = Vec::new();
    for line in no_crlf.split('\n') {
        if line.starts_with("Last sync: ") {
            normalized_lines.push("Last sync: <timestamp>".to_string());
        } else {
            normalized_lines.push(line.to_string());
        }
    }
    normalized_lines.join("\n").trim().to_string()
}

// ---------------------------------------------------------------------------
// JSON dump estilo Python json.dumps(indent=2[, ensure_ascii])
// ---------------------------------------------------------------------------

/// `json.dumps(data, indent=2)` (ensure_ascii=True por defecto en Python:
/// escapa no-ASCII como \uXXXX).
pub fn json_dump_ascii(value: &Value) -> String {
    let pretty = serde_json::to_string_pretty(value).expect("JSON serializable");
    escape_non_ascii(&pretty)
}

/// `json.dumps(data, indent=2, ensure_ascii=False)`.
pub fn json_dump_utf8(value: &Value) -> String {
    serde_json::to_string_pretty(value).expect("JSON serializable")
}

fn escape_non_ascii(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        let cp = ch as u32;
        if cp > 0x7E {
            if cp > 0xFFFF {
                // Python json usa pares surrogate \udXXX\udXXX (hex lowercase).
                let v = cp - 0x10000;
                let hi = 0xD800 + (v >> 10);
                let lo = 0xDC00 + (v & 0x3FF);
                out.push_str(&format!("\\u{hi:04x}\\u{lo:04x}"));
            } else {
                out.push_str(&format!("\\u{cp:04x}"));
            }
        } else {
            out.push(ch);
        }
    }
    out
}

/// `platform.system() != "Linux"` shortcut para tests: en fixtures nunca hay
/// WSL; los adapters usan [`needs_wsl_shielding`] + este chequeo.
/// NOTA P8d: `_create_shielded_wrapper` no se portea — solo es alcanzable
/// bajo WSL real (`_is_wsl() == true`), y los gates de paridad corren con
/// fixtures donde nunca se dispara.
pub fn is_wsl() -> bool {
    false
}

/// Detección de layout nuevo (workspace.yaml layout_version >= 2) reutilizada
/// por prompts.rs; espejo del Case 1 de WorkspaceLayout.discover.
pub fn is_new_layout(project_root: &Path) -> bool {
    let ws = project_root.join(".cortex").join("workspace.yaml");
    if ws.is_file() {
        if let Ok(content) = std::fs::read_to_string(&ws) {
            for line in content.lines() {
                if let Some(rest) = line.trim().strip_prefix("layout_version:") {
                    if rest.trim().parse::<i64>().map(|v| v >= 2).unwrap_or(false) {
                        return true;
                    }
                }
            }
        }
    }
    false
}
