"""
cortex.setup.templates
----------------------
Template system for files generated by ``cortex setup``.

Generates project-aware defaults for:
- config.yaml
- GitHub Actions workflows (ci-feature, ci-pull-request, cd-deploy)
- Vault starter docs (architecture, decisions, runbooks)
- devsecdocops.sh script
"""

from __future__ import annotations

from cortex.enterprise.config import build_enterprise_org_config, render_enterprise_config_yaml
from cortex.git_policy import recommended_gitignore_snippet
from cortex.setup.detector import ProjectContext

# ---------------------------------------------------------------------------
# config.yaml template
# ---------------------------------------------------------------------------

def render_config_yaml(ctx: ProjectContext) -> str:
    """Render config.yaml with project-aware defaults."""
    # Choose embedding provider based on detected env vars
    provider = "none"
    model = ""
    if ctx.env.has_openai_key:
        provider = "openai"
        model = "text-embedding-3-small"

    return f"""\
# Cortex configuration — auto-generated by `cortex setup`
# Project: {ctx.stack.project_name} ({ctx.stack.language})

episodic:
  persist_dir: .memory/chroma
  collection_name: cortex_episodic
  embedding_model: all-MiniLM-L6-v2
  embedding_backend: onnx  # onnx | local | openai
  namespace_mode: project  # project | branch | custom
  namespace_value: ""

semantic:
  vault_path: vault

retrieval:
  top_k: 5
  episodic_weight: 1.0
  semantic_weight: 1.0

llm:
  provider: {provider}
  model: "{model}"

integrations:
  jira:
    enabled: false
    base_url: ""
    email_env: JIRA_EMAIL
    token_env: JIRA_API_TOKEN
"""


def render_org_yaml(ctx: ProjectContext, profile: str = "small-company") -> str:
    """Render .cortex/org.yaml with a baseline enterprise topology."""
    config = build_enterprise_org_config(
        project_name=ctx.stack.project_name or ctx.root.name,
        profile=profile,  # type: ignore[arg-type]
        github_actions_enabled=ctx.ci.has_github_actions,
        branch_isolation_enabled=False,
    )
    return render_enterprise_config_yaml(config)


def render_enterprise_vault_readme(ctx: ProjectContext) -> str:
    """Render a small enterprise vault landing page."""
    project_name = ctx.stack.project_name or ctx.root.name
    return f"""\
---
title: Enterprise Memory Vault
tags: [cortex, enterprise-memory, governance]
created: 2026-04-26
---

# Enterprise Memory Vault

This vault stores durable organization-level knowledge for `{project_name}`.

## Intended content

- Architecture decisions shared across projects
- Stable runbooks and operating procedures
- Business and delivery patterns worth reusing
- Incidents and lessons with organization-wide impact

## Notes

- Project-local working memory still belongs in each repository's `vault/` and `.memory/`.
- Promotion into this vault should be deliberate and reviewable.
"""


# ---------------------------------------------------------------------------
# GitHub Actions workflow templates
# ---------------------------------------------------------------------------

def render_ci_pull_request(ctx: ProjectContext) -> str:
    """Render the PR validation workflow with Cortex integration."""
    test_cmd = _get_test_command(ctx)
    lint_cmd = _get_lint_command(ctx)
    audit_cmd = _get_audit_command(ctx)
    install_cmd = _get_install_command(ctx)
    setup_lang = _get_setup_language(ctx)

    return f"""\
name: CI - Pull Requests (DevSecDocOps)

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  quality-and-security-gate:
    name: Quality & Security Gate + Cortex Memory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

{setup_lang}

      - name: Install project dependencies
        run: {install_cmd}

      - name: Install Cortex memory
        run: pip install cortex-memory

      - name: Cortex - Doctor
        run: cortex doctor

      # ── CORTEX: Load Agent Guidelines ──────────────────────────────
      - name: Cortex — Agent Guidelines
        if: always()
        run: |
          if [ -f ".cortex/AGENT.md" ]; then
            echo "✅ Agent guidelines found in .cortex/AGENT.md"
          else
            echo "⚠ No agent guidelines found"
            echo "   Run 'cortex setup' to create them"
          fi
        continue-on-error: true

      # ── CORTEX: Capture PR Context ──────────────────────────────
      - name: Cortex — Capture PR Context
        run: |
          cortex pr-context capture \\
            --title "${{{{ github.event.pull_request.title }}}}" \\
            --body "${{{{ github.event.pull_request.body || '' }}}}" \\
            --author "${{{{ github.event.pull_request.user.login }}}}" \\
            --branch "${{{{ github.event.pull_request.head.ref }}}}" \\
            --commit "${{{{ github.event.pull_request.head.sha }}}}" \\
            --pr-number "${{{{ github.event.pull_request.number }}}}" \\
            --target-branch "${{{{ github.event.pull_request.base.ref }}}}" \\
            --labels "${{{{ join(github.event.pull_request.labels.*.name, ',') }}}}" \\
            --output .pr-context.json

      # ── LINT ───────────────────────────────────────────────────
      - name: Run Linting
        run: {lint_cmd}
        id: lint
        continue-on-error: true

      - name: Cortex — Store Lint Result
        if: always()
        run: |
          LINT_STATUS="${{{{ steps.lint.outcome }}}}"
          cortex pr-context store \\
            --context-file .pr-context.json \\
            --lint-result "$LINT_STATUS"

      # ── AUDIT / SCA ────────────────────────────────────────────
      - name: Audit Dependencies
        run: {audit_cmd}
        id: audit
        continue-on-error: true

      - name: Cortex — Store Audit Result
        if: always()
        run: |
          AUDIT_STATUS="${{{{ steps.audit.outcome }}}}"
          cortex pr-context store \\
            --context-file .pr-context.json \\
            --audit-result "$AUDIT_STATUS"

      # ── SECURITY: Secret Scanning ──────────────────────────────
      - name: Secret Scanning (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        continue-on-error: true

      # ── TESTS ──────────────────────────────────────────────────
      - name: Run Tests
        run: {test_cmd}
        id: tests
        continue-on-error: true

      - name: Cortex — Store Test Result
        if: always()
        run: |
          TEST_STATUS="${{{{ steps.tests.outcome }}}}"
          cortex pr-context store \\
            --context-file .pr-context.json \\
            --test-result "$TEST_STATUS"

      # ── CORTEX: Verify Agent Documentation ─────────────────────
      - name: Cortex — Verify Agent Docs
        if: always()
        id: verify_docs
        run: |
          HAS_DOCS=$(cortex verify-docs --vault vault --output .doc-status.json)
          echo "has_agent_docs=$HAS_DOCS" >> $GITHUB_OUTPUT
        continue-on-error: true

      # ── CORTEX: Index Agent Docs (if found) ─────────────────────
      - name: Cortex — Index Agent Docs
        if: always() && steps.verify_docs.outputs.has_agent_docs == 'true'
        run: |
          cortex index-docs --vault vault
          echo "✅ Agent documentation found and indexed"
        continue-on-error: true

      # ── CORTEX: Generate Fallback (if no agent docs) ────────────
      - name: Cortex — Generate Fallback Docs
        if: always() && steps.verify_docs.outputs.has_agent_docs != 'true'
        run: |
          cortex pr-context generate \\
            --context-file .pr-context.json \\
            --vault vault
          echo "⚠️ No agent docs — fallback documentation generated"
        continue-on-error: true

      # ── CORTEX: Search Past Context ────────────────────────────
      - name: Cortex — Search Past Context
        if: always()
        run: |
          cortex pr-context search \\
            --context-file .pr-context.json \\
            --output .past-context.json
        continue-on-error: true

      - name: Cortex - Validate Docs
        if: always()
        run: |
          cortex validate-docs \\
            --vault vault \\
            --output .doc-validation.json

      # ── CORTEX: Enrich Context (Proactive) ─────────────────────
      - name: Cortex — Enrich Context
        if: always()
        id: enrich_context
        run: |
          cortex context \\
            --files $(cat .pr-context.json | python -c "import sys,json; print(' '.join(json.load(sys.stdin).get('files_changed',[])))") \\
            --format json \\
            --output .context-enriched.json
        continue-on-error: true

      # ── CORTEX: Comment PR with Enriched Context ───────────────
      - name: Cortex — Comment PR with Enriched Context
        if: always() && steps.enrich_context.outcome == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {{
              const context = JSON.parse(fs.readFileSync('.context-enriched.json', 'utf8'));
              if (context.items && context.items.length > 0) {{
                const body = `🧠 **Cortex Context** — Found ${{context.items.length}} related memories\n\n` +
                  context.items.map((item, i) => {{
                    const source = item.source === 'episodic' ? '📝' : '📖';
                    const title = item.display_title || 'Untitled Memory';
                    return `${{source}} **${{i+1}}. ${{title}}**\\n> ${{item.content.substring(0, 200)}}` +
                      (item.content.length > 200 ? '…' : '');
                  }}).join('\\n\\n');
                github.rest.issues.createComment({{
                  issue_number: context.work.pr_number || process.env.PR_NUMBER,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body
                }});
              }}
            }} catch (e) {{
              console.log('Could not comment enriched context:', e.message);
            }}
        env:
          PR_NUMBER: ${{{{ github.event.pull_request.number }}}}
        continue-on-error: true

      # ── CORTEX: Sync Vault ─────────────────────────────────────
      - name: Cortex — Sync Vault
        if: always()
        run: cortex sync-vault

      # ── Upload Context Artifact ────────────────────────────────
      - name: Upload Cortex Context Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cortex-pr-context-${{{{ github.event.pull_request.number }}}}
          path: |
            .pr-context.json
            .past-context.json
            .doc-validation.json
          retention-days: 7

      # ── Enforce Gates ──────────────────────────────────────────
      - name: Check Lint Gate
        if: steps.lint.outcome != 'success'
        run: |
          echo "❌ Lint check failed. Fix issues before merging."
          exit 1

      - name: Check Audit Gate
        if: steps.audit.outcome != 'success'
        run: |
          echo "❌ Audit found vulnerabilities. Fix before merging."
          exit 1

      - name: Check Test Gate
        if: steps.tests.outcome != 'success'
        run: |
          echo "❌ Tests failed. Fix before merging."
          exit 1
"""


def render_ci_enterprise_governance(ctx: ProjectContext) -> str:
    """
    Render an enterprise governance workflow.

    This workflow is ci_profile-aware (observability/advisory/enforced) and
    produces stable JSON artifacts for promotion and enterprise vault health.
    """
    setup_lang = _get_setup_language(ctx)
    install_cmd = _get_install_command(ctx)

    return f"""\
name: CI - Enterprise Governance

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  enterprise-governance:
    name: Enterprise Governance (ci_profile-aware)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

{setup_lang}

      - name: Install project dependencies
        run: {install_cmd}

      - name: Install Cortex memory
        run: pip install cortex-memory

      - name: Resolve enterprise ci_profile
        id: ci_profile
        run: |
          python - <<'PY'
          import os
          from pathlib import Path
          import yaml
          path = Path(".cortex/org.yaml")
          profile = "observability"
          if path.exists():
              payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {{}}
              profile = ((payload.get("governance") or {{}}).get("ci_profile") or profile)
          profile = str(profile).strip().lower()
          if profile not in {{"observability","advisory","enforced"}}:
              profile = "observability"
          print(f"ci_profile={{profile}}")
          with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as f:
              f.write(f"ci_profile={{profile}}\\n")
          PY

      - name: Cortex - Doctor (enterprise)
        id: doctor
        continue-on-error: ${{{{ steps.ci_profile.outputs.ci_profile == 'observability' }}}}
        run: cortex doctor --scope enterprise

      - name: Cortex - Promotion Plan (dry-run)
        id: promotion_plan
        continue-on-error: ${{{{ steps.ci_profile.outputs.ci_profile != 'enforced' }}}}
        run: |
          cortex promote-knowledge --dry-run --json > .promotion-plan.json

      - name: Cortex - Sync Enterprise Vault
        id: sync_enterprise
        continue-on-error: ${{{{ steps.ci_profile.outputs.ci_profile == 'observability' }}}}
        run: |
          cortex sync-enterprise-vault --json --output .enterprise-doc-validation.json > .enterprise-sync.json

      - name: Upload Enterprise Governance Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cortex-enterprise-governance-${{{{ github.event.pull_request.number || github.run_id }}}}
          path: |
            .promotion-plan.json
            .enterprise-doc-validation.json
            .enterprise-sync.json
          retention-days: 7

      - name: Governance Summary
        if: always()
        run: |
          python - <<'PY'
          import json
          from pathlib import Path

          plan = {{}}
          if Path(".promotion-plan.json").exists():
              plan = json.loads(Path(".promotion-plan.json").read_text(encoding="utf-8"))
          planned = plan.get("planned") or []

          ent = {{}}
          if Path(".enterprise-doc-validation.json").exists():
              ent = json.loads(Path(".enterprise-doc-validation.json").read_text(encoding="utf-8"))
          errors = int(ent.get("error_count") or 0)
          warnings = int(ent.get("warning_count") or 0)

          print("Enterprise Governance Summary")
          print("---------------------------")
          print(f"Promotion candidates (ready): {{len(planned)}}")
          print(f"Enterprise vault validation: errors={{errors}} warnings={{warnings}}")
          if errors:
              files = ent.get("files") or []
              bad = [f for f in files if (f.get('error_count') or 0) > 0]
              for item in bad[:5]:
                  print(f" - {{item.get('file','(unknown)')}}: {{item.get('error_count')}} error(s)")
          PY

      - name: Enforce (enforced profile)
        if: steps.ci_profile.outputs.ci_profile == 'enforced'
        run: |
          python - <<'PY'
          import json
          from pathlib import Path

          plan = json.loads(Path(".promotion-plan.json").read_text(encoding="utf-8")) if Path(".promotion-plan.json").exists() else {{}}
          planned = plan.get("planned") or []
          if planned:
              raise SystemExit(f"Enforced governance: {{len(planned)}} promotion candidate(s) ready. Review/promote before merge.")

          ent = json.loads(Path(".enterprise-doc-validation.json").read_text(encoding="utf-8")) if Path(".enterprise-doc-validation.json").exists() else {{}}
          errors = int(ent.get("error_count") or 0)
          if errors:
              raise SystemExit(f"Enforced governance: enterprise vault has {{errors}} validation error(s).")
          PY
"""


def render_ci_feature(ctx: ProjectContext) -> str:
    """Render the feature branch CI workflow."""
    test_cmd = _get_test_command(ctx)
    lint_cmd = _get_lint_command(ctx)
    install_cmd = _get_install_command(ctx)
    setup_lang = _get_setup_language(ctx)

    return f"""\
name: CI - Feature Branch

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
      - '!main'

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

{setup_lang}

      - name: Install project dependencies
        run: {install_cmd}

      - name: Install Cortex memory
        run: pip install cortex-memory

      - name: Cortex - Doctor
        run: cortex doctor

      - name: Run Linting
        run: {lint_cmd}
        id: lint
        continue-on-error: true

      - name: Cortex — Store Lint Result
        if: always()
        run: |
          cortex remember "CI lint result: ${{{{ steps.lint.outcome }}}}" \\
            --type ci \\
            --tag lint \\
            --tag ${{{{ steps.lint.outcome }}}} \\
            --branch ${{{{ github.ref_name }}}}

      - name: Run Tests
        run: {test_cmd}
        id: tests
        continue-on-error: true

      - name: Cortex — Store Test Result
        if: always()
        run: |
          cortex remember "CI test result: ${{{{ steps.tests.outcome }}}}" \\
            --type ci \\
            --tag tests \\
            --tag ${{{{ steps.tests.outcome }}}} \\
            --branch ${{{{ github.ref_name }}}}

      - name: Cortex - Validate Docs
        if: always()
        run: cortex validate-docs --vault vault --output .doc-validation.json

      - name: Check Lint
        if: steps.lint.outcome != 'success'
        run: |
          echo "❌ Lint failed on feature branch."
          exit 1

      - name: Check Tests
        if: steps.tests.outcome != 'success'
        run: |
          echo "❌ Tests failed on feature branch."
          exit 1
"""


def render_cd_deploy(ctx: ProjectContext) -> str:
    """Render the CD deployment workflow with Cortex integration."""
    install_cmd = _get_install_command(ctx)
    setup_lang = _get_setup_language(ctx)

    return f"""\
name: CD - Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

{setup_lang}

      - name: Install project dependencies
        run: {install_cmd}

      - name: Install Cortex memory
        run: pip install cortex-memory

      - name: Cortex — Capture Deployment Context
        run: |
          cortex remember "Deploy to production: ${{{{ github.event.head_commit.message }}}}" \\
            --type deployment \\
            --tag deploy \\
            --tag production \\
            --commit ${{{{ github.sha }}}}

      - name: Deploy
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here

      - name: Cortex — Store Deployment Result
        if: always()
        run: |
          cortex remember "Deployment completed: ${{{{ job.status }}}}" \\
            --type deployment \\
            --tag deploy \\
            --tag ${{{{ job.status }}}}
"""


# ---------------------------------------------------------------------------
# Vault starter docs
# ---------------------------------------------------------------------------

def render_architecture_md(ctx: ProjectContext) -> str:
    return f"""\
---
title: Architecture Overview
tags: [architecture, system-design]
created: 2026-04-13
---

# Architecture Overview — {ctx.stack.project_name}

> High-level system architecture and design decisions.

## Tech Stack

- **Language**: {ctx.stack.language}
- **Package Manager**: {ctx.stack.package_manager}
- **Frameworks**: {', '.join(ctx.stack.frameworks) if ctx.stack.frameworks else 'None detected'}

## System Diagram

```
// Add your architecture diagram here
```

## Key Components

| Component | Responsibility | Notes |
|-----------|---------------|-------|
| | | |

## Data Flow

1.
2.
3.

## Dependencies

- External services:
- Third-party APIs:
- Message queues:

## Design Decisions

See [[decisions]] for a log of architectural decisions.
"""


def render_decisions_md(ctx: ProjectContext) -> str:
    return """\
---
title: Architecture Decision Records (ADRs)
tags: [adr, architecture, decisions]
created: 2026-04-13
---

# Architecture Decision Records

> Log of significant technical decisions and their rationale.

## ADR-001: Initialize Cortex Memory System

- **Status**: Accepted
- **Date**: 2026-04-13
- **Context**: Need persistent memory for AI agents and CI/CD pipelines.
- **Decision**: Adopt Cortex hybrid memory system (episodic + semantic).
- **Consequences**:
  - CI/CD pipeline results are stored as episodic memories
  - Documentation auto-generated into vault
  - Hybrid RRF search enables context-aware retrieval for agents

---

## Template: New ADR

Copy this template for each new decision:

### ADR-NNN: Title

- **Status**: Proposed | Accepted | Deprecated | Superseded
- **Date**: YYYY-MM-DD
- **Context**: What is the issue/decision we're facing?
- **Decision**: What did we decide?
- **Consequences**: What are the trade-offs and impacts?
"""


def render_runbooks_md(ctx: ProjectContext) -> str:
    test_cmd = _get_test_command(ctx)
    lint_cmd = _get_lint_command(ctx)

    return f"""\
---
title: Runbooks
tags: [runbook, ops, procedures]
created: 2026-04-13
---

# Runbooks

> Standard operating procedures for common tasks and incidents.

## Local Development

```bash
# Install dependencies
{_get_install_command(ctx)}

# Run tests
{test_cmd}

# Run linting
{lint_cmd}

# Build
{_get_build_command(ctx)}
```

## CI/CD Pipeline

The pipeline is integrated with Cortex memory:
- Every PR auto-generates documentation in `vault/`
- CI results stored as episodic memories (searchable)
- Hybrid RRF search finds similar past PRs
- `cortex doctor` validates the local operating state
- `cortex validate-docs` checks vault markdown integrity before merge

### Pipeline Status

Check GitHub Actions: [Actions Tab](../../actions)

## Common Issues

### Tests Failing in CI

1. Run tests locally: `{test_cmd}`
2. Check for environment differences
3. Search Cortex for similar failures: `cortex search "test failure"`

### Lint Errors

1. Run lint locally: `{lint_cmd}`
2. Auto-fix if possible: `{lint_cmd} --fix` (if supported)
3. Check lint rules configuration

### Deployment Issues

1. Check deployment logs
2. Verify environment variables
3. Search Cortex for past deployment issues: `cortex search "deploy"`

## Security Procedures

- Dependency vulnerabilities: `npm audit` or `pip audit`
- Secret rotation procedures
- Incident response checklist

## Governance Quick Checks

```bash
cortex doctor
cortex webgraph doctor --project-root .
cortex validate-docs --vault vault
```

## Adding a New Runbook

Add new procedures to this file or create separate files in `vault/runbooks/`.
Link them here using [[wiki-links]].
"""


def render_enterprise_runbook_md(ctx: ProjectContext) -> str:
    return f"""\
---
title: Cortex Enterprise Runbook
tags: [runbook, governance, onboarding]
created: 2026-04-26
---

# Cortex Enterprise Runbook

> Shared operating model for small-to-medium engineering teams using Cortex.

## Role Onboarding

### DevOps

- Run `cortex setup pipeline` in the governed repository.
- Validate baseline health with `cortex doctor`.
- Wire CI to run `cortex verify-docs` and `cortex validate-docs`.
- Keep `.memory/` local-only and never publish Chroma state.

### Developers

- Start with `cortex-sync` before implementation work.
- Persist specs in `vault/specs/` and session outcomes in `vault/sessions/`.
- Use `cortex search` and `cortex context` before repeating old work.
- Use branch namespaces when the repository has long-lived parallel work.

### Analysts

- Use `cortex webgraph serve --project-root <repo>` for one project.
- Use `cortex webgraph serve --workspace-file .cortex/webgraph/workspace.yaml` for multi-project analysis.
- Filter WebGraph by project, node type and recent activity to reduce noise.

### Staff / Tech Leads

- Review `vault/decisions/` for architectural drift.
- Keep `vault/runbooks/` current when delivery or operations change.
- Decide explicitly whether session notes are Git-tracked in your team policy.

## Daily Checks

```bash
cortex doctor
cortex validate-docs --vault vault
```

## Release and Incident Readiness

- Confirm `vault/specs/`, `vault/decisions/`, `vault/runbooks/` and `vault/hu/` are current.
- Confirm local-only state remains outside Git (`.memory/`, transient session churn if your policy ignores it).
- Re-run `cortex doctor --strict` before publishing tooling changes.

## Project Notes

- Project: {ctx.stack.project_name}
- Language: {ctx.stack.language}
- Package manager: {ctx.stack.package_manager}
"""


def render_git_vault_policy_md(ctx: ProjectContext) -> str:
    del ctx
    return f"""\
---
title: Cortex Git and Vault Policy
tags: [runbook, governance, git]
created: 2026-04-26
---

# Cortex Git and Vault Policy

## Recommended Tracking Matrix

- Track `vault/specs/`
- Track `vault/decisions/`
- Track `vault/runbooks/`
- Track `vault/hu/`
- Track `vault/incidents/`
- Ignore `vault/sessions/` by default unless your team explicitly audits session history in Git
- Ignore `.memory/` and any Chroma persistence artifacts

## Recommended `.gitignore` Snippet

```gitignore
{recommended_gitignore_snippet()}
```

## Policy Notes

- `vault/sessions/` is operational history, so it can create high churn. Teams may choose to track it, but the default recommendation is to keep it local.
- `vault/specs/`, `vault/decisions/` and `vault/runbooks/` are durable knowledge and should usually be reviewed like code.
- Imported work items in `vault/hu/` are useful shared context and should normally be versioned.
"""


# ---------------------------------------------------------------------------
# devsecdocops.sh (kept as-is, it's already a solid script)
# ---------------------------------------------------------------------------

DEVSECDOCSOPS_SCRIPT = """\
#!/usr/bin/env bash
#
# devsecdocops.sh — DevSecDocOps Orchestrator
#
# Se ejecuta en el workflow de PR y coordina:
# 1. Captura del PR → 2. Pipeline checks → 3. Doc generation → 4. Vault sync
#

set -euo pipefail

VAULT_PATH="${CORTEX_VAULT_PATH:-vault}"
CONTEXT_FILE="${CORTEX_CONTEXT_FILE:-.pr-context.json}"
PAST_CONTEXT_FILE="${CORTEX_PAST_CONTEXT_FILE:-.past-context.json}"

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

usage() {
    cat << 'EOF'
Usage: devsecdocops.sh <command> [options]

Commands:
  capture    Capture PR metadata
  store      Store pipeline results
  search     Search for similar past PRs
  generate   Generate documentation
  full       Run complete pipeline
EOF
}

parse_options() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --title) TITLE="$2"; shift 2 ;;
            --body) BODY="$2"; shift 2 ;;
            --author) AUTHOR="$2"; shift 2 ;;
            --branch) BRANCH="$2"; shift 2 ;;
            --commit) COMMIT="$2"; shift 2 ;;
            --pr-number) PR_NUMBER="$2"; shift 2 ;;
            --target-branch) TARGET_BRANCH="$2"; shift 2 ;;
            --labels) LABELS="$2"; shift 2 ;;
            --lint-result) LINT_RESULT="$2"; shift 2 ;;
            --audit-result) AUDIT_RESULT="$2"; shift 2 ;;
            --test-result) TEST_RESULT="$2"; shift 2 ;;
            --help|-h) usage; exit 0 ;;
            *) log_error "Unknown option: $1"; usage; exit 1 ;;
        esac
    done
}

cmd_capture() {
    parse_options "$@"
    log_info "Capturing PR context..."
    cortex pr-context capture \\
        --title "${TITLE:-Untitled PR}" \\
        --body "${BODY:-}" \\
        --author "${AUTHOR:-unknown}" \\
        --branch "${BRANCH:-}" \\
        --commit "${COMMIT:-}" \\
        --pr-number "${PR_NUMBER:-0}" \\
        --target-branch "${TARGET_BRANCH:-main}" \\
        --labels "${LABELS:-}" \\
        --output "$CONTEXT_FILE"
    log_ok "PR context captured -> $CONTEXT_FILE"
}

cmd_store() {
    parse_options "$@"
    log_info "Storing PR context..."
    if [[ ! -f "$CONTEXT_FILE" ]]; then
        log_error "Context file not found. Run 'capture' first."; exit 1
    fi
    cortex pr-context store \\
        --context-file "$CONTEXT_FILE" \\
        --lint-result "${LINT_RESULT:-}" \\
        --audit-result "${AUDIT_RESULT:-}" \\
        --test-result "${TEST_RESULT:-}"
    log_ok "PR context stored"
}

cmd_search() {
    parse_options "$@"
    log_info "Searching past PRs..."
    if [[ ! -f "$CONTEXT_FILE" ]]; then
        log_error "Context file not found. Run 'capture' first."; exit 1
    fi
    cortex pr-context search \\
        --context-file "$CONTEXT_FILE" \\
        --output "$PAST_CONTEXT_FILE"
    log_ok "Search saved -> $PAST_CONTEXT_FILE"
}

cmd_generate() {
    parse_options "$@"
    log_info "Generating docs..."
    if [[ ! -f "$CONTEXT_FILE" ]]; then
        log_error "Context file not found. Run 'capture' first."; exit 1
    fi
    cortex pr-context generate \\
        --context-file "$CONTEXT_FILE" \\
        --vault "$VAULT_PATH"
    log_ok "Documentation generated"
}

cmd_full() {
    parse_options "$@"
    log_info "═══════════════════════════════════════════════"
    log_info "🧠 Cortex DevSecDocOps — Full Pipeline"
    log_info "═══════════════════════════════════════════════"
    cmd_capture "$@"; echo ""
    cmd_store "$@"; echo ""
    cmd_search "$@"; echo ""
    cmd_generate "$@"; echo ""
    log_info "Syncing vault..."
    cortex sync-vault
    log_ok "Vault synced"
    echo ""
    log_info "═══════════════════════════════════════════════"
    log_ok "✅ Pipeline complete"
    log_info "═══════════════════════════════════════════════"
}

if [[ $# -lt 1 ]]; then usage; exit 1; fi
COMMAND="$1"; shift
case "$COMMAND" in
    capture)  cmd_capture "$@" ;;
    store)    cmd_store "$@" ;;
    search)   cmd_search "$@" ;;
    generate) cmd_generate "$@" ;;
    full)     cmd_full "$@" ;;
    help|-h|--help) usage; exit 0 ;;
    *) log_error "Unknown command: $COMMAND"; usage; exit 1 ;;
esac
"""


# ---------------------------------------------------------------------------
# Helper functions for project-aware commands
# ---------------------------------------------------------------------------

def _get_test_command(ctx: ProjectContext) -> str:
    if ctx.stack.test_command:
        return ctx.stack.test_command
    pt = ctx.stack.language
    if pt == "python":
        return "pytest"
    if pt in ("javascript", "typescript"):
        return "npm test"
    if pt == "go":
        return "go test ./..."
    if pt == "rust":
        return "cargo test"
    if pt == "java":
        return "mvn test"
    return "echo 'no test command detected'"


def _get_lint_command(ctx: ProjectContext) -> str:
    if ctx.stack.lint_command:
        return ctx.stack.lint_command
    pt = ctx.stack.language
    if pt in ("javascript", "typescript"):
        return "npm run lint || true"
    if pt == "python":
        return "ruff check . || true"
    if pt == "go":
        return "golangci-lint run || true"
    if pt == "rust":
        return "cargo clippy || true"
    return "echo 'no lint command detected'"


def _get_audit_command(ctx: ProjectContext) -> str:
    pt = ctx.stack.language
    if pt in ("javascript", "typescript"):
        return "npm audit --omit=dev --audit-level=high || true"
    if pt == "python":
        return "pip audit || true"
    if pt == "go":
        return "govulncheck ./... || true"
    return "echo 'no audit command for this stack'"


def _get_install_command(ctx: ProjectContext) -> str:
    pm = ctx.stack.package_manager
    if pm == "npm":
        return "npm ci"
    if pm == "yarn":
        return "yarn install --frozen-lockfile"
    if pm == "pnpm":
        return "pnpm install --frozen-lockfile"
    if pm == "pip" or pm == "pipenv" or pm == "poetry":
        return "pip install -r requirements.txt"
    if pm == "go":
        return "go mod download"
    if pm == "cargo":
        return "cargo build"
    return "echo 'install dependencies'"


def _get_build_command(ctx: ProjectContext) -> str:
    if ctx.stack.build_command:
        return ctx.stack.build_command
    pt = ctx.stack.language
    if pt in ("javascript", "typescript"):
        return "npm run build"
    if pt == "python":
        return "python -m build"
    if pt == "go":
        return "go build ./..."
    if pt == "rust":
        return "cargo build --release"
    return "echo 'no build command'"


def _get_setup_language(ctx: ProjectContext) -> str:
    """Return GitHub Actions setup steps for the detected language."""
    pt = ctx.stack.language
    if pt in ("javascript", "typescript"):
        return """\
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
"""
    if pt == "python":
        return """\
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
"""
    if pt == "go":
        return """\
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
"""
    if pt == "java" or pt == "kotlin":
        return """\
      - name: Setup Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
"""
    if pt == "ruby":
        return """\
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
"""
    return ""
