from __future__ import annotations

import json
from pathlib import Path

from cortex.ide import get_supported_ides
from cortex.ide.registry import get_adapter


def test_supported_ides_registry() -> None:
    ides = get_supported_ides()
    assert "opencode" in ides
    assert "cursor" in ides
    assert "vscode" in ides
    assert "windsurf" in ides
    assert "antigravity" not in ides
    assert "hermes" not in ides
    assert "zed" not in ides


def test_opencode_adapter_inject_profiles(monkeypatch, tmp_path: Path) -> None:
    project_root = tmp_path / "project"
    
    # Mock home dir for the adapter to write to
    monkeypatch.setattr("cortex.ide.adapters.opencode.Path.home", staticmethod(lambda: tmp_path))

    adapter = get_adapter("opencode")
    prompts = {
        "cortex-sync": "Pre-flight prompt",
        "cortex-SDDwork": "Orchestrator prompt"
    }

    files = adapter.inject_profiles(project_root, prompts)

    config_path = tmp_path / ".config" / "opencode" / "opencode.json"
    assert config_path.exists()
    assert str(config_path) in files

    data = json.loads(config_path.read_text(encoding="utf-8"))

    # Assert basic structure
    assert "cortex-sync" in data["agent"]
    assert "cortex-SDDwork" in data["agent"]
    
    # Check that tools are correctly enabled
    assert data["agent"]["cortex-sync"]["tools"]["cortex_sync_ticket"] is True
    assert data["agent"]["cortex-sync"]["tools"]["write"] is False
    assert data["agent"]["cortex-SDDwork"]["tools"]["Task"] is True
    assert data["agent"]["cortex-SDDwork"]["tools"]["edit"] is True
    assert data["agent"]["cortex-SDDwork"]["tools"]["write"] is True

    # Check that the files were written
    skills_dir = tmp_path / ".config" / "opencode" / "skills"
    sync_content = (skills_dir / "cortex-sync.md").read_text(encoding="utf-8")
    work_content = (skills_dir / "cortex-SDDwork.md").read_text(encoding="utf-8")
    
    assert "AUTOGENERATED BY CORTEX" in sync_content
    assert "Pre-flight prompt" in sync_content
    assert "AUTOGENERATED BY CORTEX" in work_content
    assert "Orchestrator prompt" in work_content


def test_opencode_adapter_inject_mcp_uses_opencode_local_command_shape(
    monkeypatch, tmp_path: Path
) -> None:
    project_root = tmp_path / "project"

    monkeypatch.setattr("cortex.ide.adapters.opencode.Path.home", staticmethod(lambda: tmp_path))
    monkeypatch.setattr("cortex.ide.base.Path.home", staticmethod(lambda: tmp_path))
    monkeypatch.setattr("cortex.ide.adapters.opencode._is_wsl", lambda: False)

    adapter = get_adapter("opencode")
    files = adapter.inject_mcp(project_root)

    config_path = tmp_path / ".config" / "opencode" / "opencode.json"
    assert config_path.exists()
    assert str(config_path) in files

    data = json.loads(config_path.read_text(encoding="utf-8"))
    cortex_config = data["mcp"]["cortex"]

    assert cortex_config["type"] == "local"
    assert cortex_config["command"] == [
        "cortex",
        "mcp-server",
        "--stdio",
        "--project-root",
        str(project_root),
    ]
    assert cortex_config["enabled"] is True
    assert cortex_config["environment"]["PYTHONWARNINGS"] == "ignore"
    assert "args" not in cortex_config
    assert "env" not in cortex_config


def test_opencode_adapter_inject_mcp_wsl_wrapper_uses_cortex_binary(
    monkeypatch, tmp_path: Path
) -> None:
    project_root = tmp_path / "project"

    monkeypatch.setattr("cortex.ide.adapters.opencode.Path.home", staticmethod(lambda: tmp_path))
    monkeypatch.setattr("cortex.ide.base.Path.home", staticmethod(lambda: tmp_path))
    monkeypatch.setattr("cortex.ide.adapters.opencode._is_wsl", lambda: True)
    monkeypatch.setattr("cortex.ide.base._is_wsl", lambda: True)
    monkeypatch.setattr("cortex.ide.base.shutil.which", lambda name: "/home/test/.local/bin/cortex")

    adapter = get_adapter("opencode")
    adapter.inject_mcp(project_root)

    config_path = tmp_path / ".config" / "opencode" / "opencode.json"
    wrapper_path = tmp_path / ".cortex" / "bin" / "cortex-mcp-wrapper"

    data = json.loads(config_path.read_text(encoding="utf-8"))
    cortex_config = data["mcp"]["cortex"]
    wrapper_content = wrapper_path.read_text(encoding="utf-8")

    assert cortex_config["command"] == [str(wrapper_path)]
    assert cortex_config["enabled"] is True
    assert wrapper_path.exists()
    assert 'exec "/home/test/.local/bin/cortex" mcp-server --stdio --project-root' in wrapper_content
    assert str(project_root) in wrapper_content
    assert "python3 -m cortex.cli.main" not in wrapper_content
    assert "PYTHONPATH" not in wrapper_content


def test_cursor_adapter_inject_mcp(monkeypatch, tmp_path: Path) -> None:
    project_root = tmp_path / "project"
    
    monkeypatch.setattr("cortex.ide.adapters.cursor.Path.home", staticmethod(lambda: tmp_path))

    adapter = get_adapter("cursor")
    files = adapter.inject_mcp(project_root)

    mcp_path = tmp_path / ".cursor" / "mcp.json"
    assert mcp_path.exists()
    assert str(mcp_path) in files

    data = json.loads(mcp_path.read_text(encoding="utf-8"))
    
    assert "cortex" in data["mcpServers"]
    assert data["mcpServers"]["cortex"]["command"] == "cortex"
    assert "mcp-server" in data["mcpServers"]["cortex"]["args"]
    assert "--stdio" in data["mcpServers"]["cortex"]["args"]
    assert "--project-root" in data["mcpServers"]["cortex"]["args"]
    assert data["mcpServers"]["cortex"]["env"]["PYTHONWARNINGS"] == "ignore"


def test_vscode_adapter_writes_workspace_agents_and_mcp(tmp_path: Path) -> None:
    project_root = tmp_path / "project"
    (project_root / ".cortex" / "subagents").mkdir(parents=True)
    (project_root / ".cortex" / "subagents" / "cortex-code-explorer.md").write_text(
        "---\nname: cortex-code-explorer\ndescription: explorer\n---\n\nExplorer body",
        encoding="utf-8",
    )
    (project_root / ".cortex" / "subagents" / "cortex-code-implementer.md").write_text(
        "---\nname: cortex-code-implementer\ndescription: implementer\n---\n\nImplementer body",
        encoding="utf-8",
    )
    (project_root / ".cortex" / "subagents" / "cortex-documenter.md").write_text(
        "---\nname: cortex-documenter\ndescription: documenter\n---\n\nDocumenter body",
        encoding="utf-8",
    )

    adapter = get_adapter("vscode")
    prompts = {
        "cortex-sync": "---\nname: cortex-sync\n---\n\nSync body",
        "cortex-SDDwork": "---\nname: cortex-SDDwork\n---\n\nWork body",
    }

    files = adapter.inject_profiles(project_root, prompts)
    files.extend(adapter.inject_mcp(project_root))

    sync_path = project_root / ".github" / "agents" / "cortex-sync.agent.md"
    work_path = project_root / ".github" / "agents" / "cortex-SDDwork.agent.md"
    mcp_path = project_root / ".vscode" / "mcp.json"

    assert sync_path.exists()
    assert work_path.exists()
    assert mcp_path.exists()
    assert str(sync_path) in files
    assert "handoffs:" in sync_path.read_text(encoding="utf-8")
    assert "agents:" in work_path.read_text(encoding="utf-8")
    assert "cortex" in json.loads(mcp_path.read_text(encoding="utf-8"))["servers"]


def test_claude_code_adapter_writes_project_assets(tmp_path: Path) -> None:
    project_root = tmp_path / "project"
    (project_root / ".cortex" / "subagents").mkdir(parents=True)
    for name in ("cortex-code-explorer", "cortex-code-implementer", "cortex-documenter"):
        (project_root / ".cortex" / "subagents" / f"{name}.md").write_text(
            f"---\nname: {name}\ndescription: {name}\n---\n\n{name} body",
            encoding="utf-8",
        )

    adapter = get_adapter("claude_code")
    prompts = {
        "cortex-sync": "---\nname: cortex-sync\n---\n\nSync body",
        "cortex-SDDwork": "---\nname: cortex-SDDwork\n---\n\nWork body",
    }

    files = adapter.inject_profiles(project_root, prompts)
    files.extend(adapter.inject_mcp(project_root))

    assert (project_root / "CLAUDE.md").exists()
    assert (project_root / ".claude" / "skills" / "cortex-sync" / "SKILL.md").exists()
    assert (project_root / ".claude" / "skills" / "cortex-sddwork" / "SKILL.md").exists()
    assert (project_root / ".claude" / "agents" / "cortex-code-explorer.md").exists()
    assert (project_root / ".mcp.json").exists()
    assert (project_root / ".claude" / "settings.json").exists()
    assert str(project_root / ".mcp.json") in files


def test_windsurf_adapter_writes_agents_md(monkeypatch, tmp_path: Path) -> None:
    project_root = tmp_path / "project"
    monkeypatch.setattr("cortex.ide.adapters.windsurf.Path.home", staticmethod(lambda: tmp_path))

    adapter = get_adapter("windsurf")
    prompts = {"cortex-sync": "sync", "cortex-SDDwork": "work"}
    files = adapter.inject_profiles(project_root, prompts)
    files.extend(adapter.inject_mcp(project_root))

    agents_path = project_root / "AGENTS.md"
    mcp_path = tmp_path / ".codeium" / "windsurf" / "mcp_config.json"

    assert agents_path.exists()
    assert mcp_path.exists()
    assert str(agents_path) in files
    assert "cortex_save_session" in agents_path.read_text(encoding="utf-8")


def test_registry_accepts_common_aliases() -> None:
    assert get_adapter("claude").name == "claude_code"
    assert get_adapter("claude-desktop").name == "claude_desktop"
